### ISSUE TITLE
dataclass variable Optional type causing issue

### ISSUE THREAD

**Issue by shawalli** [Dobiasd/undictify#2]
Not quite sure why this is happening, but when using an Optional dataclass variable, the unpacker is blowing up. The deepest I managed to dig was that the traceback was referring the the Union object, but that it's only arguments were `*args, **kwds` (see below for more reference).

# Code
```python
import json
from typing import Callable, TypeVar, Optional

from dataclasses import dataclass

from undictify import type_checked_apply_skip_convert

TypeT = TypeVar('TypeT')

def unpack_json(target_func: Callable[..., TypeT], data: str) -> TypeT:
    return type_checked_apply_skip_convert(target_func, **json.loads(data))


@dataclass
class Point:
  x: int
  y: int

@dataclass
class Rect:
  left: Point
  right: Point
  top: Point
  bottom: Optional[Point]

data_json = """
{
  "label" : "square",
  "left": {
    "x": 3,
    "y": 2,
    "z": 1
  },
  "right": {
    "x": 3,
    "y": 2
  },
  "top": {
    "x": 3,
    "y": 2
  },
  "bottom": {
    "x": 3,
    "y": 2
  }
}
"""

r = unpack_json(Rect, data_json)
print(r)
```

# Stack Trace
```python
Traceback (most recent call last):
  File "scratch.py", line 49, in <module>
    r = unpack_json(Rect, data_json)
  File "scratch.py", line 11, in unpack_json
    return type_checked_apply_skip_convert(target_func, **json.loads(data))
  File "/Users/shawalli/scratch/venv/lib/python3.7/site-packages/undictify/_unpack.py", line 90, in type_checked_apply_skip_convert
    True, True)
  File "/Users/shawalli/scratch/venv/lib/python3.7/site-packages/undictify/_unpack.py", line 153, in __unpack_dict
    convert_types)
  File "/Users/shawalli/scratch/venv/lib/python3.7/site-packages/undictify/_unpack.py", line 173, in __get_value
    return __unpack_dict(target_type, value, convert_types)
  File "/Users/shawalli/scratch/venv/lib/python3.7/site-packages/undictify/_unpack.py", line 136, in __unpack_dict
    raise TypeError('Only parameters of kind POSITIONAL_OR_KEYWORD '
TypeError: Only parameters of kind POSITIONAL_OR_KEYWORD supported in target functions.
```

# PDB Data
```python
>>>  func
typing.Union[__main__.Point, NoneType]
>>>  param.kind
<_ParameterKind.VAR_POSITIONAL: 2>
>>>  signature.parameters
mappingproxy(OrderedDict([('args', <Parameter "*args">), ('kwds', <Parameter "**kwds">)]))
```

**Comment by Dobiasd** [comment]
Thanks a lot for this very good error report.

In the end it had nothing to with dataclasses, but with `Optional[CustomClass]`. This is now (version 0.2.2) supported and covered with unit tests.

After installing the latest version, your code should work.

Sorry for the trouble again, and I really appreciate your feedback. Error reports like this are extremely helpful for improving the quality of the library. :+1:

Please let me know if you run into any other troubles.

---

But additionaly to solving the actual problem I'd like to make a remark to your data structure. :wink:

From a geometrical point of view the thing you have there is not a rectangle in the vast majority of cases.

A (upright) rectangle has exactly 4 degrees of freedom typically expressed as:

```python
class Point:
    x: int
    y: int

class Rect:
    top_left: Point
    bottom_right: Point
```

or as:

```python
class Rect:
    top: int
    left: int
    width: int
    height: int
```

If we allow the rect to be rotated, there are 5 degrees of freedom, which can be expressed for example like this:

```python
class Point:
    x: int
    y: int

class RotatedRect:
    center: Point
    width: int
    height: int
    angle_deg: float
```

The thing you have there with 6 degrees of freedom is not a rectangle but might for example be a rotated parallelogram.

In case of the optional being used you have 8 degrees of freedom, which is an arbitrary 4-sided polygon.
