### ISSUE TITLE
Future-compatible annotations

### ISSUE THREAD

**Issue by LukeMathWalker** [Dobiasd/undictify#8]
Here I come again :stuck_out_tongue: 

I have been happily using `undictify` and everything works properly... until I do:
```
from __future__ import annotations
```
in Python 3.7.
If I have a simple class like:
```
@type_checked_constructor(convert=True, skip=True):
class Example:
    a: str
```
and I try to instantiate it I get a "`str` is not a function" complaint, because I assume the annotations stops being callable. :thinking:

**Comment by LukeMathWalker** [comment]
Full reproducible example:
```python
from __future__ import annotations
from undictify import type_checked_constructor
from typing import NamedTuple

@type_checked_constructor(convert=True, skip=True)
class Example(NamedTuple):
    a: str

if __name__=="__main__":
    Example(a="text")
```

Stacktrace:
```
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    Example(a="text")
  File "/home/luca/.local/share/virtualenvs/py-merchant-manager-gH-ASn0_/lib/python3.7/site-packages/undictify/_unpack.py", line 65, in wrapper
    convert)
  File "/home/luca/.local/share/virtualenvs/py-merchant-manager-gH-ASn0_/lib/python3.7/site-packages/undictify/_unpack.py", line 182, in _unpack_dict
    convert_types)
  File "/home/luca/.local/share/virtualenvs/py-merchant-manager-gH-ASn0_/lib/python3.7/site-packages/undictify/_unpack.py", line 214, in _get_value
    return func(value)
TypeError: 'str' object is not callable
```

**Comment by Dobiasd** [comment]
Interesting! I can confirm the error of the minimal example, and that the problem vanishes if I remove either `from __future__ import annotations` or `@type_checked_constructor(convert=True, skip=True)`.

It seems [`from __future__ import annotations`](https://docs.python.org/3/library/__future__.html) activates [PEP 563 -- Postponed Evaluation of Annotations](https://www.python.org/dev/peps/pep-0563/). Since I never heard about this before, I'll read it up, and then dive into debugging and get back to you. :)

**Comment by LukeMathWalker** [comment]
Thanks a lot for looking into this :)

**Comment by Dobiasd** [comment]
[WIP](https://stackoverflow.com/questions/53390985/inspect-signature-with-pep-563) :wink:

**Comment by Dobiasd** [comment]
@LukeMathWalker [Python is a strange beast](https://stackoverflow.com/questions/53450624/hasattr-telling-lies-attributeerror-method-object-has-no-attribute-annot), but it's working now. ;)

**Comment by LukeMathWalker** [comment]
You have just saved me from circular import errors and ugly workaround. Thanks a lot!
On 23 Nov 2018, at 17:55, Tobias Hermann <notifications@github.com<mailto:notifications@github.com>> wrote:

@LukeMathWalker<https://github.com/LukeMathWalker> Python is a strange beast<https://stackoverflow.com/questions/53450624/hasattr-telling-lies-attributeerror-method-object-has-no-attribute-annot>, but it's working now. ;)
